version: "3.7"

services:
  db:
    image: postgres:alpine
    restart: always
    env_file: "Core/.env"
    ports:
      - 5432:5432
  core:
    build: Core
    command: ./core
    depends_on:
    - db
    restart: always
    ports:
      - "3003:8080"
