version: "3"

services:
  auth:
    build: Authorization
    restart: always
    ports:
      - "3001:8080"
    depends_on:
      - database
    networks:
      - foodway
  core:
    build: Core
    restart: always
    ports:
      - "3003:8080"
    depends_on:
      - database
    networks:
      - foodway
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
    - foodway
    environment:
      POSTGRES_USER: foodway
      POSTGRES_PASSWORD: foodwaypass
      POSTGRES_DB: foodway
#  admin:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    networks:
#    - foodway
#    ports:
#      - "8080:8080"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: test@main.ru
      PGADMIN_DEFAULT_PASSWORD: foodwaypass
    depends_on:
      - database
    ports:
      - "8080:8081"
    networks:
      - foodway
    restart: unless-stopped
volumes:
  data:

networks:
  foodway:
    driver: bridge