version: "3"

services:
  bus:
    build: Authentification
    ports:
      - "80:8080"
  auth:
    build: Authorization
    ports:
      - "3001:8080"
  static_app:
    build: StaticApp
    ports:
      - "3002:8080"
  core:
    build: Core
    ports:
      - "3003:8080"
