FROM golang:1.19-buster
ENV GOPATH=/

COPY ./ ./

# install psql
RUN apt-get update
RUN apt-get -y install postgresql-client

RUN go mod download
RUN go build -o core cmd/api/main.go

CMD [ "./core" ]
